"%test":
  quarkus:
    jacoco:
      title: lysense test coverage report

  lysense:
    configuration:
      default: classpath:/configuration/test-default-configuration.yaml
      min-base-version: 0.0.0

lysense:
  configuration:
    default: classpath:/assets/default-configuration.yaml