quarkus:
  banner:
    enabled: false
  log:
    category:
      "io.quarkus":
        level: warn
      "com.norcane.lysense":
        level: ${LYSENSE_LOG_LEVEL:off}
  native:
    resources:
      includes:
        - embedded/**
    additional-build-args:
      - --initialize-at-run-time=org.jline.nativ.JLineLibrary
      - --initialize-at-run-time=org.jline.nativ.CLibrary
      - --initialize-at-run-time=org.jline.nativ.CLibrary$WinSize
      - --initialize-at-run-time=org.jline.nativ.CLibrary$Termios
      - -J--enable-preview

lysense:
  configuration:
    default: classpath:/embedded/default-configuration.yaml
    min-base-version: 0.0.0

## TEST CONFIGURATION
"%test":
  quarkus:
    jacoco:
      title: lysense test coverage report

  lysense:
    configuration:
      default: classpath:/configuration/test-default-configuration.yaml
      min-base-version: 0.0.0