quarkus:
  banner:
    enabled: false
  log:
    category:
      "io.quarkus":
        level: warn
      "com.norcane.lysense":
        level: ${LYSENSE_LOG_LEVEL:off}
  native:
    resources:
      includes:
        - embedded/**
    additional-build-args:
      - --initialize-at-run-time=org.jline.nativ.JLineLibrary
      - --initialize-at-run-time=org.jline.nativ.CLibrary
      - --initialize-at-run-time=org.jline.nativ.CLibrary$WinSize
      - --initialize-at-run-time=org.jline.nativ.CLibrary$Termios
      - --initialize-at-run-time=org.jline.nativ.Kernel32
      - --initialize-at-run-time=org.jline.nativ.Kernel32$INPUT_RECORD
      - --initialize-at-run-time=org.jline.nativ.Kernel32$MENU_EVENT_RECORD
      - --initialize-at-run-time=org.jline.nativ.Kernel32$FOCUS_EVENT_RECORD
      - --initialize-at-run-time=org.jline.nativ.Kernel32$WINDOW_BUFFER_SIZE_RECORD
      - --initialize-at-run-time=org.jline.nativ.Kernel32$MOUSE_EVENT_RECORD
      - --initialize-at-run-time=org.jline.nativ.Kernel32$KEY_EVENT_RECORD
      - --initialize-at-run-time=org.jline.nativ.Kernel32$CHAR_INFO
      - --initialize-at-run-time=org.jline.nativ.Kernel32$CONSOLE_SCREEN_BUFFER_INFO
      - --initialize-at-run-time=org.jline.nativ.Kernel32$COORD
      - --initialize-at-run-time=org.jline.nativ.Kernel32$SMALL_RECT

lysense:
  configuration:
    default: classpath:/embedded/default-configuration.yaml
    min-base-version: 0.0.0

## TEST CONFIGURATION
"%test":
  quarkus:
    jacoco:
      title: lysense test coverage report

  lysense:
    configuration:
      default: classpath:/configuration/test-default-configuration.yaml
      min-base-version: 0.0.0